version: "3.7"

services:
  parsedmarc:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-main
    build:
      context: ./parsedmarc
    restart: unless-stopped

  elasticsearch:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-elasticsearch
    build:
      context: ./elasticsearch
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/:z
    restart: unless-stopped

  kibana:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-kibana
    image: docker.elastic.co/kibana/kibana:7.4.2
    build:
      context: ./kibana
    restart: unless-stopped

  nginx:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-nginx
    build:
      context: ./nginx
    restart: unless-stopped