version: "3.8"

services:
  parsedmarc:
    container_name: "parsedmarc"
    build:
      context: ./parsedmarc
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "parsedmarc-data:/usr/share/elasticsearch/data"
    restart: unless-stopped

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      - server.name=parsedmarc
      - server.host="0"
      - elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch

volumes:
  parsedmarc-data:
    external: true

networks:
  default:
    external:
      name: prodeko-docker-net
