version: "3.8"

services:
  parsedmarc:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-main
    build:
      context: ./parsedmarc
    restart: unless-stopped

  elasticsearch:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-elasticsearch
    build:
      context: ./elasticsearch
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/:z
    restart: unless-stopped

  kibana:
    image: prodekoregistry.azurecr.io/parsedmarc/parsedmarc-kibana
    build:
      context: ./kibana
    restart: unless-stopped

networks:
  default:
    external:
      name: prodeko-docker-net
