name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy project
        uses: ./.github/workflows/deploy
